export const defaultEmojiIconGroup1 = [
  {
    id: 7037089,
    name: "点赞",
    pyName: "dianzan",
    type: "default",
    group: 1,
    path: "https://moose-plus.oss-cn-shenzhen.aliyuncs.com/emoji/1/dianzan.png",
  },
  {
    id: 6901410,
    name: "啊",
    pyName: "a",
    type: "default",
    group: 1,
    path: "https://moose-plus.oss-cn-shenzhen.aliyuncs.com/emoji/1/a.png",
  },
  {
    id: 6901411,
    name: "闭嘴",
    pyName: "bizui",
    type: "default",
    group: 1,
    path: "https://moose-plus.oss-cn-shenzhen.aliyuncs.com/emoji/1/bizui.png",
  },
  {
    id: 6901412,
    name: "白眼",
    pyName: "baiyan",
    type: "default",
    group: 1,
    path: "https://moose-plus.oss-cn-shenzhen.aliyuncs.com/emoji/1/baiyan.png",
  },
  {
    id: 6901413,
    name: "爱心",
    pyName: "aixin",
    type: "default",
    group: 1,
    path: "https://moose-plus.oss-cn-shenzhen.aliyuncs.com/emoji/1/aixin.png",
  },
  {
    id: 6901414,
    name: "大惊",
    pyName: "dajing",
    type: "default",
    group: 1,
    path: "https://moose-plus.oss-cn-shenzhen.aliyuncs.com/emoji/1/dajing.png",
  },
  {
    id: 6901415,
    name: "呲牙",
    pyName: "ziya",
    type: "default",
    group: 1,
    path: "https://moose-plus.oss-cn-shenzhen.aliyuncs.com/emoji/1/ziya.png",
  },
  {
    id: 6901416,
    name: "大笑",
    pyName: "daxiao",
    type: "default",
    group: 1,
    path: "https://moose-plus.oss-cn-shenzhen.aliyuncs.com/emoji/1/daxiao.png",
  },
  {
    id: 6901417,
    name: "饿死",
    pyName: "esi",
    type: "default",
    group: 1,
    path: "https://moose-plus.oss-cn-shenzhen.aliyuncs.com/emoji/1/esi.png",
  },
  {
    id: 6901418,
    name: "发呆",
    pyName: "fadai",
    type: "default",
    group: 1,
    path: "https://moose-plus.oss-cn-shenzhen.aliyuncs.com/emoji/1/fadai.png",
  },
  {
    id: 6901419,
    name: "犯困",
    pyName: "fankun",
    type: "default",
    group: 1,
    path: "https://moose-plus.oss-cn-shenzhen.aliyuncs.com/emoji/1/fankun.png",
  },
  {
    id: 6901420,
    name: "尴尬",
    pyName: "ganga",
    type: "default",
    group: 1,
    path: "https://moose-plus.oss-cn-shenzhen.aliyuncs.com/emoji/1/ganga.png",
  },
  {
    id: 6901421,
    name: "愤怒",
    pyName: "fennu",
    type: "default",
    group: 1,
    path: "https://moose-plus.oss-cn-shenzhen.aliyuncs.com/emoji/1/fennu.png",
  },
  {
    id: 6901422,
    name: "汗颜",
    pyName: "hanyan",
    type: "default",
    group: 1,
    path: "https://moose-plus.oss-cn-shenzhen.aliyuncs.com/emoji/1/hanyan.png",
  },
  {
    id: 6901423,
    name: "惊恐",
    pyName: "jingkong",
    type: "default",
    group: 1,
    path: "https://moose-plus.oss-cn-shenzhen.aliyuncs.com/emoji/1/jingkong.png",
  },
  {
    id: 6901424,
    name: "好吃",
    pyName: "haochi",
    type: "default",
    group: 1,
    path: "https://moose-plus.oss-cn-shenzhen.aliyuncs.com/emoji/1/haochi.png",
  },
  {
    id: 6901425,
    name: "恶魔",
    pyName: "emo",
    type: "default",
    group: 1,
    path: "https://moose-plus.oss-cn-shenzhen.aliyuncs.com/emoji/1/emo.png",
  },
  {
    id: 6901426,
    name: "惊悚",
    pyName: "jingsong",
    type: "default",
    group: 1,
    path: "https://moose-plus.oss-cn-shenzhen.aliyuncs.com/emoji/1/jingsong.png",
  },
  {
    id: 6901427,
    name: "惊讶",
    pyName: "jingya",
    type: "default",
    group: 1,
    path: "https://moose-plus.oss-cn-shenzhen.aliyuncs.com/emoji/1/jingya.png",
  },
  {
    id: 6901428,
    name: "开心",
    pyName: "kaixin",
    type: "default",
    group: 1,
    path: "https://moose-plus.oss-cn-shenzhen.aliyuncs.com/emoji/1/kaixin.png",
  },
  {
    id: 6901429,
    name: "冷酷",
    pyName: "lengku",
    type: "default",
    group: 1,
    path: "https://moose-plus.oss-cn-shenzhen.aliyuncs.com/emoji/1/lengku.png",
  },
  {
    id: 6901430,
    name: "大闹",
    pyName: "danao",
    type: "default",
    group: 1,
    path: "https://moose-plus.oss-cn-shenzhen.aliyuncs.com/emoji/1/danao.png",
  },
  {
    id: 6901431,
    name: "流口水",
    pyName: "liukoushui",
    type: "default",
    group: 1,
    path: "https://moose-plus.oss-cn-shenzhen.aliyuncs.com/emoji/1/liukoushui.png",
  },
  {
    id: 6901432,
    name: "流泪",
    pyName: "liulei",
    type: "default",
    group: 1,
    path: "https://moose-plus.oss-cn-shenzhen.aliyuncs.com/emoji/1/liulei.png",
  },
  {
    id: 6901433,
    name: "懵逼",
    pyName: "mengbi",
    type: "default",
    group: 1,
    path: "https://moose-plus.oss-cn-shenzhen.aliyuncs.com/emoji/1/mengbi.png",
  },
  {
    id: 6901434,
    name: "面无表情",
    pyName: "mianwubiaoqing",
    type: "default",
    group: 1,
    path: "https://moose-plus.oss-cn-shenzhen.aliyuncs.com/emoji/1/mianwubiaoqing.png",
  },
  {
    id: 6901435,
    name: "难过",
    pyName: "nanguo",
    type: "default",
    group: 1,
    path: "https://moose-plus.oss-cn-shenzhen.aliyuncs.com/emoji/1/nanguo.png",
  },
  {
    id: 6901436,
    name: "睡着",
    pyName: "shuizhuo",
    type: "default",
    group: 1,
    path: "https://moose-plus.oss-cn-shenzhen.aliyuncs.com/emoji/1/shuizhuo.png",
  },
  {
    id: 6901437,
    name: "讨厌",
    pyName: "taoyan",
    type: "default",
    group: 1,
    path: "https://moose-plus.oss-cn-shenzhen.aliyuncs.com/emoji/1/taoyan.png",
  },
  {
    id: 6901438,
    name: "贪吃",
    pyName: "tanchi",
    type: "default",
    group: 1,
    path: "https://moose-plus.oss-cn-shenzhen.aliyuncs.com/emoji/1/tanchi.png",
  },
  {
    id: 6901440,
    name: "调皮",
    pyName: "tiaopi",
    type: "default",
    group: 1,
    path: "https://moose-plus.oss-cn-shenzhen.aliyuncs.com/emoji/1/tiaopi.png",
  },
  {
    id: 6901442,
    name: "笑出泪",
    pyName: "xiaochulei",
    type: "default",
    group: 1,
    path: "https://moose-plus.oss-cn-shenzhen.aliyuncs.com/emoji/1/xiaochulei.png",
  },
  {
    id: 6901443,
    name: "无聊",
    pyName: "wuliao",
    type: "default",
    group: 1,
    path: "https://moose-plus.oss-cn-shenzhen.aliyuncs.com/emoji/1/wuliao.png",
  },
  {
    id: 6901444,
    name: "星星眼",
    pyName: "xingxingyan",
    type: "default",
    group: 1,
    path: "https://moose-plus.oss-cn-shenzhen.aliyuncs.com/emoji/1/xingxingyan.png",
  },
  {
    id: 6901445,
    name: "斜眼",
    pyName: "xieyan",
    type: "default",
    group: 1,
    path: "https://moose-plus.oss-cn-shenzhen.aliyuncs.com/emoji/1/xieyan.png",
  },
  {
    id: 6901446,
    name: "吓死",
    pyName: "xiasi",
    type: "default",
    group: 1,
    path: "https://moose-plus.oss-cn-shenzhen.aliyuncs.com/emoji/1/xiasi.png",
  },
  {
    id: 6901447,
    name: "笑脸",
    pyName: "xiaolian",
    type: "default",
    group: 1,
    path: "https://moose-plus.oss-cn-shenzhen.aliyuncs.com/emoji/1/xiaolian.png",
  },
  {
    id: 7027206,
    name: "酷",
    pyName: "ku",
    type: "default",
    group: 1,
    path: "https://moose-plus.oss-cn-shenzhen.aliyuncs.com/emoji/1/ku.png",
  },
  {
    id: 7027794,
    name: "生气",
    pyName: "shengqi",
    type: "default",
    group: 1,
    path: "https://moose-plus.oss-cn-shenzhen.aliyuncs.com/emoji/1/shengqi.png",
  },
  {
    id: 6901439,
    name: "死了",
    pyName: "siliao",
    type: "default",
    group: 1,
    path: "https://moose-plus.oss-cn-shenzhen.aliyuncs.com/emoji/1/siliao.png",
  },
  {
    id: 7027812,
    name: "又死了",
    pyName: "yousiliao",
    type: "default",
    group: 1,
    path: "https://moose-plus.oss-cn-shenzhen.aliyuncs.com/emoji/1/yousiliao.png",
  },
  {
    id: 7035577,
    name: "恩",
    pyName: "en",
    type: "default",
    group: 1,
    path: "https://moose-plus.oss-cn-shenzhen.aliyuncs.com/emoji/1/en.png",
  },
  {
    id: 7035578,
    name: "不舒服",
    pyName: "bushufu",
    type: "default",
    group: 1,
    path: "https://moose-plus.oss-cn-shenzhen.aliyuncs.com/emoji/1/bushufu.png",
  },
  {
    id: 7035579,
    name: "便便",
    pyName: "bianbian",
    type: "default",
    group: 1,
    path: "https://moose-plus.oss-cn-shenzhen.aliyuncs.com/emoji/1/bianbian.png",
  },
  {
    id: 7035580,
    name: "犯困",
    pyName: "fankun",
    type: "default",
    group: 1,
    path: "https://moose-plus.oss-cn-shenzhen.aliyuncs.com/emoji/1/fankun.png",
  },
  {
    id: 7035581,
    name: "飞吻",
    pyName: "feiwen",
    type: "default",
    group: 1,
    path: "https://moose-plus.oss-cn-shenzhen.aliyuncs.com/emoji/1/feiwen.png",
  },
  {
    id: 7035582,
    name: "感冒",
    pyName: "ganmao",
    type: "default",
    group: 1,
    path: "https://moose-plus.oss-cn-shenzhen.aliyuncs.com/emoji/1/ganmao.png",
  },
  {
    id: 7035583,
    name: "坏笑",
    pyName: "huaixiao",
    type: "default",
    group: 1,
    path: "https://moose-plus.oss-cn-shenzhen.aliyuncs.com/emoji/1/huaixiao.png",
  },
  {
    id: 7035584,
    name: "流汗",
    pyName: "liuhan",
    type: "default",
    group: 1,
    path: "https://moose-plus.oss-cn-shenzhen.aliyuncs.com/emoji/1/liuhan.png",
  },
  {
    id: 7035585,
    name: "呕吐",
    pyName: "outu",
    type: "default",
    group: 1,
    path: "https://moose-plus.oss-cn-shenzhen.aliyuncs.com/emoji/1/outu.png",
  },
  {
    id: 7035586,
    name: "瞌睡",
    pyName: "keshui",
    type: "default",
    group: 1,
    path: "https://moose-plus.oss-cn-shenzhen.aliyuncs.com/emoji/1/keshui.png",
  },
  {
    id: 7035587,
    name: "忍者",
    pyName: "renzhe",
    type: "default",
    group: 1,
    path: "https://moose-plus.oss-cn-shenzhen.aliyuncs.com/emoji/1/renzhe.png",
  },
  {
    id: 7035588,
    name: "三条线",
    pyName: "santiaoxian",
    type: "default",
    group: 1,
    path: "https://moose-plus.oss-cn-shenzhen.aliyuncs.com/emoji/1/santiaoxian.png",
  },
  {
    id: 7035589,
    name: "怪物",
    pyName: "guaiwu",
    type: "default",
    group: 1,
    path: "https://moose-plus.oss-cn-shenzhen.aliyuncs.com/emoji/1/guaiwu.png",
  },
  {
    id: 7035590,
    name: "受伤",
    pyName: "shoushang",
    type: "default",
    group: 1,
    path: "https://moose-plus.oss-cn-shenzhen.aliyuncs.com/emoji/1/shoushang.png",
  },
  {
    id: 7035591,
    name: "天使",
    pyName: "tianshi",
    type: "default",
    group: 1,
    path: "https://moose-plus.oss-cn-shenzhen.aliyuncs.com/emoji/1/tianshi.png",
  },
  {
    id: 7035592,
    name: "衰",
    pyName: "shuai",
    type: "default",
    group: 1,
    path: "https://moose-plus.oss-cn-shenzhen.aliyuncs.com/emoji/1/shuai.png",
  },
  {
    id: 7035593,
    name: "献吻",
    pyName: "xianwen",
    type: "default",
    group: 1,
    path: "https://moose-plus.oss-cn-shenzhen.aliyuncs.com/emoji/1/xianwen.png",
  },
  {
    id: 7035594,
    name: "笑掉大牙",
    pyName: "xiaodiaodaya",
    type: "default",
    group: 1,
    path: "https://moose-plus.oss-cn-shenzhen.aliyuncs.com/emoji/1/xiaodiaodaya.png",
  },
  {
    id: 7035595,
    name: "凶",
    pyName: "xiong",
    type: "default",
    group: 1,
    path: "https://moose-plus.oss-cn-shenzhen.aliyuncs.com/emoji/1/xiong.png",
  },
  {
    id: 7035596,
    name: "疑问",
    pyName: "yiwen",
    type: "default",
    group: 1,
    path: "https://moose-plus.oss-cn-shenzhen.aliyuncs.com/emoji/1/yiwen.png",
  },
  {
    id: 7035597,
    name: "晕",
    pyName: "yun",
    type: "default",
    group: 1,
    path: "https://moose-plus.oss-cn-shenzhen.aliyuncs.com/emoji/1/yun.png",
  },
  {
    id: 7035750,
    name: "流鼻血",
    pyName: "liubixie",
    type: "default",
    group: 1,
    path: "https://moose-plus.oss-cn-shenzhen.aliyuncs.com/emoji/1/liubixie.png",
  },
  {
    id: 7036579,
    name: "什么",
    pyName: "shimo",
    type: "default",
    group: 1,
    path: "https://moose-plus.oss-cn-shenzhen.aliyuncs.com/emoji/1/shimo.png",
  },
  {
    id: 7042352,
    name: "鼻涕",
    pyName: "biti",
    type: "default",
    group: 1,
    path: "https://moose-plus.oss-cn-shenzhen.aliyuncs.com/emoji/1/biti.png",
  },
  {
    id: 7042353,
    name: "奋斗",
    pyName: "fendou",
    type: "default",
    group: 1,
    path: "https://moose-plus.oss-cn-shenzhen.aliyuncs.com/emoji/1/fendou.png",
  },
  {
    id: 7042354,
    name: "呼气",
    pyName: "huqi",
    type: "default",
    group: 1,
    path: "https://moose-plus.oss-cn-shenzhen.aliyuncs.com/emoji/1/huqi.png",
  },
  {
    id: 7042355,
    name: "哼",
    pyName: "heng",
    type: "default",
    group: 1,
    path: "https://moose-plus.oss-cn-shenzhen.aliyuncs.com/emoji/1/heng.png",
  },
  {
    id: 7042356,
    name: "骷髅",
    pyName: "kulou",
    type: "default",
    group: 1,
    path: "https://moose-plus.oss-cn-shenzhen.aliyuncs.com/emoji/1/kulou.png",
  },
  {
    id: 7042357,
    name: "冷",
    pyName: "leng",
    type: "default",
    group: 1,
    path: "https://moose-plus.oss-cn-shenzhen.aliyuncs.com/emoji/1/leng.png",
  },
  {
    id: 7042359,
    name: "讨厌",
    pyName: "taoyan",
    type: "default",
    group: 1,
    path: "https://moose-plus.oss-cn-shenzhen.aliyuncs.com/emoji/1/taoyan.png",
  },
  {
    id: 7042360,
    name: "睡醒",
    pyName: "shuixing",
    type: "default",
    group: 1,
    path: "https://moose-plus.oss-cn-shenzhen.aliyuncs.com/emoji/1/shuixing.png",
  },
  {
    id: 7045191,
    name: "爱你",
    pyName: "aini",
    type: "default",
    group: 1,
    path: "https://moose-plus.oss-cn-shenzhen.aliyuncs.com/emoji/1/aini.png",
  },
  {
    id: 7049102,
    name: "爱慕",
    pyName: "aimu",
    type: "default",
    group: 1,
    path: "https://moose-plus.oss-cn-shenzhen.aliyuncs.com/emoji/1/aimu.png",
  },
  {
    id: 7049103,
    name: "炸弹",
    pyName: "zhadan",
    type: "default",
    group: 1,
    path: "https://moose-plus.oss-cn-shenzhen.aliyuncs.com/emoji/1/zhadan.png",
  },
  {
    id: 7049104,
    name: "心碎",
    pyName: "xinsui",
    type: "default",
    group: 1,
    path: "https://moose-plus.oss-cn-shenzhen.aliyuncs.com/emoji/1/xinsui.png",
  },
  {
    id: 7049363,
    name: "骂人",
    pyName: "maren",
    type: "default",
    group: 1,
    path: "https://moose-plus.oss-cn-shenzhen.aliyuncs.com/emoji/1/maren.png",
  },
  {
    id: 7082722,
    name: "猪头",
    pyName: "zhutou",
    type: "default",
    group: 1,
    path: "https://moose-plus.oss-cn-shenzhen.aliyuncs.com/emoji/1/zhutou.png",
  },
  {
    id: 7082723,
    name: "企鹅",
    pyName: "qie",
    type: "default",
    group: 1,
    path: "https://moose-plus.oss-cn-shenzhen.aliyuncs.com/emoji/1/qie.png",
  },
  {
    id: 7082724,
    name: "幽灵",
    pyName: "youling",
    type: "default",
    group: 1,
    path: "https://moose-plus.oss-cn-shenzhen.aliyuncs.com/emoji/1/youling.png",
  },
];

export const defaultEmojiIconGroup2 = [
  {
    type: "default",
    group: 2,
    name: "大笑",
    pyName: "daxiao",
    path: "https://moose-plus.oss-cn-shenzhen.aliyuncs.com/emoji/2/daxiao.png",
    id: 6901409,
  },
  {
    type: "default",
    group: 2,
    name: "开心",
    pyName: "kaixin",
    path: "https://moose-plus.oss-cn-shenzhen.aliyuncs.com/emoji/2/kaixin.png",
    id: 6901408,
  },
  {
    type: "default",
    group: 2,
    name: "献吻",
    pyName: "xiangwen",
    path: "https://moose-plus.oss-cn-shenzhen.aliyuncs.com/emoji/2/xiangwen.png",
    id: 6901407,
  },
  {
    type: "default",
    group: 2,
    name: "流鼻子",
    pyName: "liubizi",
    path: "https://moose-plus.oss-cn-shenzhen.aliyuncs.com/emoji/2/liubizi.png",
    id: 6901406,
  },
  {
    type: "default",
    group: 2,
    name: "财迷",
    pyName: "caimi",
    path: "https://moose-plus.oss-cn-shenzhen.aliyuncs.com/emoji/2/caimi.png",
    id: 6901405,
  },
  {
    type: "default",
    group: 2,
    name: "开怀大笑",
    pyName: "kaihuaidaxiao",
    path: "https://moose-plus.oss-cn-shenzhen.aliyuncs.com/emoji/2/kaihuaidaxiao.png",
    id: 6901404,
  },
  {
    type: "default",
    group: 2,
    name: "无空",
    pyName: "wukong",
    path: "https://moose-plus.oss-cn-shenzhen.aliyuncs.com/emoji/2/wukong.png",
    id: 6901403,
  },
  {
    type: "default",
    group: 2,
    name: "佛系",
    pyName: "foxi",
    path: "https://moose-plus.oss-cn-shenzhen.aliyuncs.com/emoji/2/foxi.png",
    id: 6901402,
  },
  {
    type: "default",
    group: 2,
    name: "可爱",
    pyName: "keai",
    path: "https://moose-plus.oss-cn-shenzhen.aliyuncs.com/emoji/2/keai.png",
    id: 6901401,
  },
  {
    type: "default",
    group: 2,
    name: "欣赏",
    pyName: "xinshang",
    path: "https://moose-plus.oss-cn-shenzhen.aliyuncs.com/emoji/2/xinshang.png",
    id: 6901400,
  },
  {
    type: "default",
    group: 2,
    name: "鼓励",
    pyName: "guli",
    path: "https://moose-plus.oss-cn-shenzhen.aliyuncs.com/emoji/2/guli.png",
    id: 6901399,
  },
  {
    type: "default",
    group: 2,
    name: "抛媚眼",
    pyName: "paomeiyan",
    path: "https://moose-plus.oss-cn-shenzhen.aliyuncs.com/emoji/2/paomeiyan.png",
    id: 6901398,
  },
  {
    type: "default",
    group: 2,
    name: "眩晕",
    pyName: "xuanyun",
    path: "https://moose-plus.oss-cn-shenzhen.aliyuncs.com/emoji/2/xuanyun.png",
    id: 6901397,
  },
  {
    type: "default",
    group: 2,
    name: "伤心",
    pyName: "shangxin",
    path: "https://moose-plus.oss-cn-shenzhen.aliyuncs.com/emoji/2/shangxin.png",
    id: 6901396,
  },
  {
    type: "default",
    group: 2,
    name: "一本正经",
    pyName: "yibenzhengjing",
    path: "https://moose-plus.oss-cn-shenzhen.aliyuncs.com/emoji/2/yibenzhengjing.png",
    id: 6901395,
  },
  {
    type: "default",
    group: 2,
    name: "震惊",
    pyName: "zhenjing",
    path: "https://moose-plus.oss-cn-shenzhen.aliyuncs.com/emoji/2/zhenjing.png",
    id: 6901394,
  },
  {
    type: "default",
    group: 2,
    name: "生气",
    pyName: "shengqi",
    path: "https://moose-plus.oss-cn-shenzhen.aliyuncs.com/emoji/2/shengqi.png",
    id: 6901393,
  },
  {
    type: "default",
    group: 2,
    name: "失望",
    pyName: "shiwang",
    path: "https://moose-plus.oss-cn-shenzhen.aliyuncs.com/emoji/2/shiwang.png",
    id: 6901392,
  },
  {
    type: "default",
    group: 2,
    name: "害怕",
    pyName: "haipa",
    path: "https://moose-plus.oss-cn-shenzhen.aliyuncs.com/emoji/2/haipa.png",
    id: 6901391,
  },
  {
    type: "default",
    group: 2,
    name: "花痴",
    pyName: "huachi",
    path: "https://moose-plus.oss-cn-shenzhen.aliyuncs.com/emoji/2/huachi.png",
    id: 6901390,
  },
  {
    type: "default",
    group: 2,
    name: "坏坏",
    pyName: "huaihuai",
    path: "https://moose-plus.oss-cn-shenzhen.aliyuncs.com/emoji/2/huaihuai.png",
    id: 6901389,
  },
];

export const collectIcons = [
  {
    name: "心动",
    type: "collect",
    id: 1000001,
    path: "https://moose-plus.oss-cn-shenzhen.aliyuncs.com/emoji/custom/xindong.gif",
  },
  {
    name: "收到",
    type: "collect",
    id: 2000001,
    path: "https://moose-plus.oss-cn-shenzhen.aliyuncs.com/emoji/custom/over.jpeg",
  },
];
